issues:
  exclude-rules:
    - linters:
      - gosimple
      text: "S1002: should omit comparison to bool constant"
    - linters:
      - revive
      text: "exported: exported const"
    # TODO(codingllama): Remove ignore after the new golangci-lint image lands.
    # For some reason this particular files causes problems between different
    # goimports versions.
    - path: lib/services/role_test.go
      linters:
      - goimports
  exclude-use-default: true
  max-same-issues: 0
  max-issues-per-linter: 0

linters:
  disable-all: true
  enable:
    - bodyclose
    - depguard
    - goimports
    - gosimple
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - unconvert
    - unused

linters-settings:
  depguard:
    list-type: denylist
    include-go-root: true # check against stdlib
    packages-with-error-message:
    - io/ioutil: 'use "io" or "os" packages instead'
    - github.com/siddontang/go/log: 'use "github.com/sirupsen/logrus" instead'
    - github.com/siddontang/go-log/log: 'use "github.com/sirupsen/logrus" instead'
  misspell:
    locale: US
output:
  uniq-by-line: false

run:
  skip-dirs-use-default: false
  timeout: 5m
  go: '1.18'
