# Proxy server for cluster "two". Also runs "node" role
version: v3
teleport:
  nodename: two-proxy
  auth_server: two-auth
  join_params:
    join_method: token
    token_name: foo
  log:
    output: stdout
    severity: DEBUG
  data_dir: /var/lib/teleport
  storage:
    path: /var/lib/teleport/backend
    type: dir

auth_service:
  enabled: no

ssh_service:
  enabled: yes
  labels:
    cluster: two
    role: proxy+node
  commands:
    - name: kernel
      command: [ /bin/uname, -r ]
      period: 5m

proxy_service:
  enabled: yes
  listen_addr: 0.0.0.0:5023
  web_listen_addr: 0.0.0.0:5080
