# See: https://google.github.io/oss-fuzz/getting-started/continuous-integration/

name: "CIFuzz"

on:
  push:
    branches:
      - master
      - branch/*
    paths:
      - '**.go'
  pull_request:
    branches:
      - master
      - branch/*
    paths:
      - '**.go'

jobs:
  fuzzing:
    name: Fuzzing
    runs-on: ubuntu-22.04-32core
    permissions:
      contents: read

    steps:
    - name: Build Fuzzers
      id: build
      uses: google/oss-fuzz/infra/cifuzz/actions/build_fuzzers@master
      with:
        oss-fuzz-project-name: 'teleport'
        language: go
    - name: Run Fuzzers
      uses: google/oss-fuzz/infra/cifuzz/actions/run_fuzzers@master
      with:
        oss-fuzz-project-name: 'teleport'
        language: go
        fuzz-seconds: 600
    - name: Upload Crash
      uses: actions/upload-artifact@v3
      if: failure() && steps.build.outcome == 'success'
      with:
        name: artifacts
        path: ./out/artifacts
